# Result Visualization

This file plots experiment run results for analysis.

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df_ttt = pd.read_csv("./__run_results/ttt.csv", converters={'session_timestamp': str})
df_ttt

,world_type,player1,player2,outcome,avg_milliseconds_per_move_player1,avg_milliseconds_per_move_player2,num_moves,session_id,session_timestamp,milliseconds,game_num
0,ttt,StrategyDefaultTTT,StrategyMiniMax,0,0.000000,6.726532,9,exp1_ttt_x_def_o_minimax,07042024041617,123.258789,1
1,ttt,StrategyDefaultTTT,StrategyMiniMax,2,0.000000,16.672867,8,exp1_ttt_x_def_o_minimax,07042024041617,235.514893,2
2,ttt,StrategyDefaultTTT,StrategyMiniMax,2,0.000000,14.314194,8,exp1_ttt_x_def_o_minimax,07042024041617,202.390869,3
3,ttt,StrategyDefaultTTT,StrategyMiniMax,0,0.000000,11.306473,9,exp1_ttt_x_def_o_minimax,07042024041617,165.269043,4
4,ttt,StrategyDefaultTTT,StrategyMiniMax,2,0.000000,11.751770,8,exp1_ttt_x_def_o_minimax,07042024041617,178.522461,5
...,...,...,...,...,...,...,...,...,...,...,...
497,ttt,StrategyMiniMax,StrategyDefaultTTT,1,58.560547,0.000000,7,exp8_ttt_x_minimax_1000_depth_o_def,07042024110525,894.367188,96
498,ttt,StrategyMiniMax,StrategyDefaultTTT,1,32.312500,0.000000,9,exp8_ttt_x_minimax_1000_depth_o_def,07042024110525,1007.698486,97
499,ttt,StrategyMiniMax,StrategyDefaultTTT,1,29.448730,0.000000,9,exp8_ttt_x_minimax_1000_depth_o_def,07042024110525,908.941895,98
500,ttt,StrategyMiniMax,StrategyDefaultTTT,1,56.252563,0.000000,7,exp8_ttt_x_minimax_1000_depth_o_def,07042024110525,860.834717,99
501,ttt,StrategyMiniMax,StrategyDefaultTTT,1,26.804512,0.000000,9,exp8_ttt_x_minimax_1000_depth_o_def,07042024110525,843.524170,100

In [17]:
df_con4 = pd.read_csv("./__run_results/con4.csv", converters={'session_timestamp': str})
df_con4

,world_type,player1,player2,outcome,avg_milliseconds_per_move_player1,avg_milliseconds_per_move_player2,num_moves,session_id,session_timestamp,milliseconds,game_num
0,con4,StrategyTabQLearning,StrategyMiniMax,2,0.000000,173.968277,8,exp4_ttt_r_qtab_y_minimax,07042024045911,861.638428,1
1,con4,StrategyTabQLearning,StrategyMiniMax,2,0.000000,165.431061,8,exp4_ttt_r_qtab_y_minimax,07042024045911,832.670410,2
2,con4,StrategyTabQLearning,StrategyMiniMax,2,0.847839,167.706665,8,exp4_ttt_r_qtab_y_minimax,07042024045911,842.580322,3
3,con4,StrategyTabQLearning,StrategyMiniMax,2,0.000000,168.935913,8,exp4_ttt_r_qtab_y_minimax,07042024045911,851.430176,4
4,con4,StrategyTabQLearning,StrategyMiniMax,2,0.249878,165.678802,8,exp4_ttt_r_qtab_y_minimax,07042024045911,847.311279,5
...,...,...,...,...,...,...,...,...,...,...,...
395,con4,StrategyRandomCon4,StrategyTabQLearning,1,0.000000,0.000000,27,exp6_con4_r_rand_y_tabq,07042024103713,0.000000,96
396,con4,StrategyRandomCon4,StrategyTabQLearning,2,0.000000,0.000000,26,exp6_con4_r_rand_y_tabq,07042024103713,16.008789,97
397,con4,StrategyRandomCon4,StrategyTabQLearning,1,0.000000,0.000000,9,exp6_con4_r_rand_y_tabq,07042024103713,0.000000,98
398,con4,StrategyRandomCon4,StrategyTabQLearning,1,0.000000,0.000000,15,exp6_con4_r_rand_y_tabq,07042024103713,0.000000,99
399,con4,StrategyRandomCon4,StrategyTabQLearning,2,0.000000,0.000000,24,exp6_con4_r_rand_y_tabq,07042024103713,15.630371,100

## Experiment 1

In [18]:
df_exp1 = df_ttt[df_ttt['session_id'].str.contains('exp1')]
df_exp1_minimax = df_exp1[df_exp1['player2'] == "StrategyMiniMax"]
df_exp1_tabq = df_exp1[df_exp1['player2'] == "StrategyTabQLearning"]

performance_summary = []

# Get performance of minimax agent.
win_rate = (sum(df_exp1_minimax['outcome'] == 2)/len(df_exp1_minimax))*100
loss_rate = (sum(df_exp1_minimax['outcome'] == 1)/len(df_exp1_minimax))*100
draw_rate = (sum(df_exp1_minimax['outcome'] == 0)/len(df_exp1_minimax))*100
avg_move_ms = df_exp1_minimax['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp1_minimax['num_moves'].mean()
ps_exp1_minimax = {}
ps_exp1_minimax['experiment'] = 1
ps_exp1_minimax['game'] = 'Tic Tac Toe'
ps_exp1_minimax['player'] = 'Minimax (Alpha Beta)'
ps_exp1_minimax['opponent'] = 'default'
ps_exp1_minimax['win_rate'] = win_rate
ps_exp1_minimax['loss_rate'] = loss_rate
ps_exp1_minimax['draw_rate'] = draw_rate
ps_exp1_minimax['avg_move_ms'] = avg_move_ms
ps_exp1_minimax['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp1_minimax)

# Get performance of q learning agent.
win_rate = (sum(df_exp1_tabq['outcome'] == 2)/len(df_exp1_tabq))*100
loss_rate = (sum(df_exp1_tabq['outcome'] == 1)/len(df_exp1_tabq))*100
draw_rate = (sum(df_exp1_tabq['outcome'] == 0)/len(df_exp1_tabq))*100
avg_move_ms = df_exp1_tabq['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp1_tabq['num_moves'].mean()
ps_exp1_tabq = {}
ps_exp1_tabq['experiment'] = 1
ps_exp1_tabq['game'] = 'Tic Tac Toe'
ps_exp1_tabq['player'] = 'Tabular Q Learning'
ps_exp1_tabq['opponent'] = 'default'
ps_exp1_tabq['win_rate'] = win_rate
ps_exp1_tabq['loss_rate'] = loss_rate
ps_exp1_tabq['draw_rate'] = draw_rate
ps_exp1_tabq['avg_move_ms'] = avg_move_ms
ps_exp1_tabq['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp1_tabq)

df_exp1_ps = pd.DataFrame(performance_summary)
df_exp1_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,1,Tic Tac Toe,Minimax (Alpha Beta),default,40.0,0.0,60.0,11.719084,8.60
1,1,Tic Tac Toe,Tabular Q Learning,default,20.0,6.0,74.0,0.030279,8.68

## Experiment 3

In [19]:
df_exp3 = df_ttt[df_ttt['session_id'].str.contains('exp3')]

performance_summary = []

# Get performance of minimax agent.
win_rate = (sum(df_exp3['outcome'] == 2)/len(df_exp3))*100
loss_rate = (sum(df_exp3['outcome'] == 1)/len(df_exp3))*100
draw_rate = (sum(df_exp3['outcome'] == 0)/len(df_exp3))*100
avg_move_ms = df_exp3['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp3['num_moves'].mean()
ps_exp3_minimax = {}
ps_exp3_minimax['experiment'] = 3
ps_exp3_minimax['game'] = 'Tic Tac Toe'
ps_exp3_minimax['player'] = 'Minimax (Alpha Beta)'
ps_exp3_minimax['opponent'] = 'Tabular Q Learning'
ps_exp3_minimax['win_rate'] = win_rate
ps_exp3_minimax['loss_rate'] = loss_rate
ps_exp3_minimax['draw_rate'] = draw_rate
ps_exp3_minimax['avg_move_ms'] = avg_move_ms
ps_exp3_minimax['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp3_minimax)

# Get performance of q learning agent.
win_rate = (sum(df_exp3['outcome'] == 1)/len(df_exp3))*100
loss_rate = (sum(df_exp3['outcome'] == 2)/len(df_exp3))*100
draw_rate = (sum(df_exp3['outcome'] == 0)/len(df_exp3))*100
avg_move_ms = df_exp3['avg_milliseconds_per_move_player1'].mean()
avg_game_moves = df_exp3['num_moves'].mean()
ps_exp3_tabq = {}
ps_exp3_tabq['experiment'] = 3
ps_exp3_tabq['game'] = 'Tic Tac Toe'
ps_exp3_tabq['player'] = 'Tabular Q Learning'
ps_exp3_tabq['opponent'] = 'Minimax (Alpha Beta)'
ps_exp3_tabq['win_rate'] = win_rate
ps_exp3_tabq['loss_rate'] = loss_rate
ps_exp3_tabq['draw_rate'] = draw_rate
ps_exp3_tabq['avg_move_ms'] = avg_move_ms
ps_exp3_tabq['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp3_tabq)

df_exp3_ps = pd.DataFrame(performance_summary)
df_exp3_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,3,Tic Tac Toe,Minimax (Alpha Beta),Tabular Q Learning,0.0,0.0,100.0,13.650460,9.0
1,3,Tic Tac Toe,Tabular Q Learning,Minimax (Alpha Beta),0.0,0.0,100.0,0.002244,9.0

## Experiment 2

In [20]:
df_exp2 = df_con4[df_con4['session_id'].str.contains('exp2')]
df_exp2_minimax = df_exp2[df_exp2['player2'] == "StrategyMiniMax"]
df_exp2_tabq = df_exp2[df_exp2['player2'] == "StrategyTabQLearning"]

performance_summary = []

# Get performance of minimax agent.
win_rate = (sum(df_exp2_minimax['outcome'] == 2)/len(df_exp2_minimax))*100
loss_rate = (sum(df_exp2_minimax['outcome'] == 1)/len(df_exp2_minimax))*100
draw_rate = (sum(df_exp2_minimax['outcome'] == 0)/len(df_exp2_minimax))*100
avg_move_ms = df_exp2_minimax['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp2_minimax['num_moves'].mean()
ps_exp2_minimax = {}
ps_exp2_minimax['experiment'] = 2
ps_exp2_minimax['game'] = 'Connect 4'
ps_exp2_minimax['player'] = 'Minimax (Alpha Beta)'
ps_exp2_minimax['opponent'] = 'default'
ps_exp2_minimax['win_rate'] = win_rate
ps_exp2_minimax['loss_rate'] = loss_rate
ps_exp2_minimax['draw_rate'] = draw_rate
ps_exp2_minimax['avg_move_ms'] = avg_move_ms
ps_exp2_minimax['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp2_minimax)

# Get performance of q learning agent.
win_rate = (sum(df_exp2_tabq['outcome'] == 2)/len(df_exp2_tabq))*100
loss_rate = (sum(df_exp2_tabq['outcome'] == 1)/len(df_exp2_tabq))*100
draw_rate = (sum(df_exp2_tabq['outcome'] == 0)/len(df_exp2_tabq))*100
avg_move_ms = df_exp2_tabq['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp2_tabq['num_moves'].mean()
ps_exp2_tabq = {}
ps_exp2_tabq['experiment'] = 2
ps_exp2_tabq['game'] = 'Connect 4'
ps_exp2_tabq['player'] = 'Tabular Q Learning'
ps_exp2_tabq['opponent'] = 'default'
ps_exp2_tabq['win_rate'] = win_rate
ps_exp2_tabq['loss_rate'] = loss_rate
ps_exp2_tabq['draw_rate'] = draw_rate
ps_exp2_tabq['avg_move_ms'] = avg_move_ms
ps_exp2_tabq['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp2_tabq)

df_exp2_ps = pd.DataFrame(performance_summary)
df_exp2_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,2,Connect 4,Minimax (Alpha Beta),default,66.0,28.0,6.0,133.887320,28.00
1,2,Connect 4,Tabular Q Learning,default,10.0,90.0,0.0,0.020238,16.22

## Experiment 4

In [21]:
df_exp4 = df_con4[df_con4['session_id'].str.contains('exp4')]

performance_summary = []

# Get performance of minimax agent.
win_rate = (sum(df_exp4['outcome'] == 2)/len(df_exp4))*100
loss_rate = (sum(df_exp4['outcome'] == 1)/len(df_exp4))*100
draw_rate = (sum(df_exp4['outcome'] == 0)/len(df_exp4))*100
avg_move_ms = df_exp4['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp4['num_moves'].mean()
ps_exp4_minimax = {}
ps_exp4_minimax['experiment'] = 4
ps_exp4_minimax['game'] = 'Connect 4'
ps_exp4_minimax['player'] = 'Minimax (Alpha Beta, Depth = 5)'
ps_exp4_minimax['opponent'] = 'Tabular Q Learning'
ps_exp4_minimax['win_rate'] = win_rate
ps_exp4_minimax['loss_rate'] = loss_rate
ps_exp4_minimax['draw_rate'] = draw_rate
ps_exp4_minimax['avg_move_ms'] = avg_move_ms
ps_exp4_minimax['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp4_minimax)

# Get performance of q learning agent.
win_rate = (sum(df_exp4['outcome'] == 1)/len(df_exp4))*100
loss_rate = (sum(df_exp4['outcome'] == 2)/len(df_exp4))*100
draw_rate = (sum(df_exp4['outcome'] == 0)/len(df_exp4))*100
avg_move_ms = df_exp4['avg_milliseconds_per_move_player1'].mean()
avg_game_moves = df_exp4['num_moves'].mean()
ps_exp4_tabq = {}
ps_exp4_tabq['experiment'] = 4
ps_exp4_tabq['game'] = 'Connect 4'
ps_exp4_tabq['player'] = 'Tabular Q Learning'
ps_exp4_tabq['opponent'] = 'Minimax (Alpha Beta)'
ps_exp4_tabq['win_rate'] = win_rate
ps_exp4_tabq['loss_rate'] = loss_rate
ps_exp4_tabq['draw_rate'] = draw_rate
ps_exp4_tabq['avg_move_ms'] = avg_move_ms
ps_exp4_tabq['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp4_tabq)

df_exp4_ps = pd.DataFrame(performance_summary)
df_exp4_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,4,Connect 4,"Minimax (Alpha Beta, Depth = 5)",Tabular Q Learning,99.0,1.0,0.0,199.241360,12.57
1,4,Connect 4,Tabular Q Learning,Minimax (Alpha Beta),1.0,99.0,0.0,0.231481,12.57

## Experiment 6

In [22]:
df_exp6 = df_con4[df_con4['session_id'].str.contains('exp6')]

performance_summary = []

# Get performance of minimax agent.
win_rate = (sum(df_exp6['outcome'] == 1)/len(df_exp6))*100
loss_rate = (sum(df_exp6['outcome'] == 2)/len(df_exp6))*100
draw_rate = (sum(df_exp6['outcome'] == 0)/len(df_exp6))*100
avg_move_ms = df_exp6['avg_milliseconds_per_move_player1'].mean()
avg_game_moves = df_exp6['num_moves'].mean()
ps_exp6_minimax = {}
ps_exp6_minimax['experiment'] = 6
ps_exp6_minimax['game'] = 'Connect 4'
ps_exp6_minimax['player'] = 'random'
ps_exp6_minimax['opponent'] = 'Tabular Q Learning'
ps_exp6_minimax['win_rate'] = win_rate
ps_exp6_minimax['loss_rate'] = loss_rate
ps_exp6_minimax['draw_rate'] = draw_rate
ps_exp6_minimax['avg_move_ms'] = avg_move_ms
ps_exp6_minimax['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp6_minimax)

# Get performance of q learning agent.
win_rate = (sum(df_exp6['outcome'] == 2)/len(df_exp6))*100
loss_rate = (sum(df_exp6['outcome'] == 1)/len(df_exp6))*100
draw_rate = (sum(df_exp6['outcome'] == 0)/len(df_exp6))*100
avg_move_ms = df_exp6['avg_milliseconds_per_move_player2'].mean()
avg_game_moves = df_exp6['num_moves'].mean()
ps_exp6_tabq = {}
ps_exp6_tabq['experiment'] = 6
ps_exp6_tabq['game'] = 'Connect 4'
ps_exp6_tabq['player'] = 'Tabular Q Learning'
ps_exp6_tabq['opponent'] = 'random'
ps_exp6_tabq['win_rate'] = win_rate
ps_exp6_tabq['loss_rate'] = loss_rate
ps_exp6_tabq['draw_rate'] = draw_rate
ps_exp6_tabq['avg_move_ms'] = avg_move_ms
ps_exp6_tabq['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp6_tabq)

df_exp6_ps = pd.DataFrame(performance_summary)
df_exp6_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,6,Connect 4,random,Tabular Q Learning,62.0,38.0,0.0,0.007031,18.04
1,6,Connect 4,Tabular Q Learning,random,38.0,62.0,0.0,0.133750,18.04

## Experiment 8

In [24]:
df_exp8 = df_ttt[df_ttt['session_id'].str.contains('exp8')]
df_exp8_minimax_low_depth = df_exp8[df_ttt['session_id'].str.contains('2_depth')]
df_exp8_minimax_high_depth = df_exp8[df_ttt['session_id'].str.contains('1000_depth')]

performance_summary = []

# Get performance of minimax agent (alpha beta pruning + low depth = 2)
win_rate = (sum(df_exp8_minimax_low_depth['outcome'] == 1)/len(df_exp8_minimax_low_depth))*100
loss_rate = (sum(df_exp8_minimax_low_depth['outcome'] == 2)/len(df_exp8_minimax_low_depth))*100
draw_rate = (sum(df_exp8_minimax_low_depth['outcome'] == 0)/len(df_exp8_minimax_low_depth))*100
avg_move_ms = df_exp8_minimax_low_depth['avg_milliseconds_per_move_player1'].mean()
avg_game_moves = df_exp8_minimax_low_depth['num_moves'].mean()
ps_exp8_minimax_low_depth = {}
ps_exp8_minimax_low_depth['experiment'] = 8
ps_exp8_minimax_low_depth['game'] = 'Tic Tac Toe'
ps_exp8_minimax_low_depth['player'] = 'Minimax (Alpha Beta + Low Depth = 2)'
ps_exp8_minimax_low_depth['opponent'] = 'default'
ps_exp8_minimax_low_depth['win_rate'] = win_rate
ps_exp8_minimax_low_depth['loss_rate'] = loss_rate
ps_exp8_minimax_low_depth['draw_rate'] = draw_rate
ps_exp8_minimax_low_depth['avg_move_ms'] = avg_move_ms
ps_exp8_minimax_low_depth['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp8_minimax_low_depth)

# Get performance of minimax agent (alpha beta pruning + high depth = 2)
win_rate = (sum(df_exp8_minimax_high_depth['outcome'] == 1)/len(df_exp8_minimax_high_depth))*100
loss_rate = (sum(df_exp8_minimax_high_depth['outcome'] == 2)/len(df_exp8_minimax_high_depth))*100
draw_rate = (sum(df_exp8_minimax_high_depth['outcome'] == 0)/len(df_exp8_minimax_high_depth))*100
avg_move_ms = df_exp8_minimax_high_depth['avg_milliseconds_per_move_player1'].mean()
avg_game_moves = df_exp8_minimax_high_depth['num_moves'].mean()
ps_exp8_minimax_high_depth = {}
ps_exp8_minimax_high_depth['experiment'] = 8
ps_exp8_minimax_high_depth['game'] = 'Tic Tac Toe'
ps_exp8_minimax_high_depth['player'] = 'Minimax (Alpha Beta + High Depth = 1000)'
ps_exp8_minimax_high_depth['opponent'] = 'default'
ps_exp8_minimax_high_depth['win_rate'] = win_rate
ps_exp8_minimax_high_depth['loss_rate'] = loss_rate
ps_exp8_minimax_high_depth['draw_rate'] = draw_rate
ps_exp8_minimax_high_depth['avg_move_ms'] = avg_move_ms
ps_exp8_minimax_high_depth['avg_game_moves'] = avg_game_moves
performance_summary.append(ps_exp8_minimax_high_depth)

df_exp8_ps = pd.DataFrame(performance_summary)
df_exp8_ps

C:\Users\g_gna\AppData\Local\Temp\ipykernel_21312\2544701901.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_exp8_minimax_low_depth = df_exp8[df_ttt['session_id'].str.contains('2_depth')]
C:\Users\g_gna\AppData\Local\Temp\ipykernel_21312\2544701901.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_exp8_minimax_high_depth = df_exp8[df_ttt['session_id'].str.contains('1000_depth')]

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,8,Tic Tac Toe,Minimax (Alpha Beta + Low Depth = 2),default,68.0,7.0,25.0,0.607177,7.89
1,8,Tic Tac Toe,Minimax (Alpha Beta + High Depth = 1000),default,98.0,0.0,2.0,50.004516,7.36

## Combine Results & Save

In [30]:
df_combined_ps = pd.concat([
    df_exp1_ps, df_exp3_ps, df_exp6_ps, df_exp8_ps, df_exp2_ps, df_exp4_ps
])
# Does not include exp 5 and exp 7.

In [29]:
# df_combined_ps.to_csv('./__run_results/performance_summary.csv', index=False)

In [31]:
df_combined_ps = pd.read_csv('./__run_results/performance_summary.csv')
df_combined_ps

,experiment,game,player,opponent,win_rate,loss_rate,draw_rate,avg_move_ms,avg_game_moves
0,1,Tic Tac Toe,Minimax (Alpha Beta),default,40.0,0.0,60.0,11.719084,8.60
1,1,Tic Tac Toe,Tabular Q Learning,default,20.0,6.0,74.0,0.030279,8.68
2,3,Tic Tac Toe,Minimax (Alpha Beta),Tabular Q Learning,0.0,0.0,100.0,13.650460,9.00
3,3,Tic Tac Toe,Tabular Q Learning,Minimax (Alpha Beta),0.0,0.0,100.0,0.002244,9.00
4,6,Connect 4,random,Tabular Q Learning,62.0,38.0,0.0,0.007031,18.04
5,6,Connect 4,Tabular Q Learning,random,38.0,62.0,0.0,0.133750,18.04
6,8,Tic Tac Toe,Minimax (Alpha Beta + Low Depth = 2),default,68.0,7.0,25.0,0.607177,7.89
7,8,Tic Tac Toe,Minimax (Alpha Beta + High Depth = 1000),default,98.0,0.0,2.0,50.004516,7.36
8,2,Connect 4,Minimax (Alpha Beta),default,66.0,28.0,6.0,133.887320,28.00
9,2,Connect 4,Tabular Q Learning,default,10.0,90.0,0.0,0.020238,16.22
10,4,Connect 4,"Minimax (Alpha Beta, Depth = 5)",Tabular Q Learning,99.0,1.0,0.0,199.241360,12.57
11,4,Connect 4,Tabular Q Learning,Minimax (Alpha Beta),1.0,99.0,0.0,0.231481,12.57