# Result Visualization

This file plots experiment run results for analysis.

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
from utility import get_datetime_id

In [13]:
get_datetime_id()

'06042024190401'

In [17]:
df = pd.read_csv("./__run_metrics/ttt.csv", converters={'session_timestamp': str})
df

,world_type,player1,player2,outcome,avg_milliseconds_per_move_player1,avg_milliseconds_per_move_player2,num_moves,session_id,session_timestamp,milliseconds,game_num,moves_visited
0,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190105,5.132080,1,NaN
1,ttt,X,O,2,0.000000,0.0,8,x_def_o_rand,06042024190105,5.356201,2,NaN
2,ttt,X,O,1,0.000000,0.0,9,x_def_o_rand,06042024190105,8.567627,3,NaN
3,ttt,X,O,1,0.000000,0.0,9,x_def_o_rand,06042024190105,7.619385,4,NaN
4,ttt,X,O,1,0.249390,0.0,5,x_def_o_rand,06042024190105,4.277588,5,NaN
5,ttt,X,O,0,0.000000,0.0,9,x_def_o_rand,06042024190105,9.577881,6,NaN
6,ttt,X,O,1,0.000000,0.0,9,x_def_o_rand,06042024190105,7.089111,7,NaN
7,ttt,X,O,2,0.000000,0.0,8,x_def_o_rand,06042024190105,7.802734,8,NaN
8,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190105,1.124756,9,NaN
9,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190105,9.909424,10,NaN
10,ttt,X,O,0,0.000000,0.0,9,x_def_o_rand,06042024190154,22.949951,1,NaN
11,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190154,6.804443,2,NaN
12,ttt,X,O,1,0.000000,0.0,9,x_def_o_rand,06042024190154,6.653564,3,NaN
13,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190154,5.123779,4,NaN
14,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190154,4.560791,5,NaN
15,ttt,X,O,1,0.000000,0.0,7,x_def_o_rand,06042024190154,4.812500,6,NaN
16,ttt,X,O,2,0.000000,0.0,8,x_def_o_rand,06042024190154,4.196533,7,NaN
17,ttt,X,O,1,0.000000,0.0,7,x_def_o_rand,06042024190154,8.242432,8,NaN
18,ttt,X,O,1,0.083221,0.0,5,x_def_o_rand,06042024190154,4.364014,9,NaN
19,ttt,X,O,1,0.000000,0.0,5,x_def_o_rand,06042024190154,4.336914,10,NaN